---
title: "Bayesian LCR Sampler with adaptive Metropolis within Gibbs"
output: html_notebook
---


```{r}
library(poLCA)
library(MCMCpack)
library(BayesLCA)
library(matrixNormal)
```

Creating function for $\gamma_{g}(\mathbf{x}_i)$
```{r}
gamma_vec <- function(beta, g, x, i, G) {
  xi <- x[i, ]                              
  betaxi <- beta %*% xi                    
  exp_betaxi <- exp(betaxi)                
  
  # Calculate the probabilitie
  q <- exp_betaxi / (1 + sum(exp_betaxi[-G]))
  
  q <- c(q[-G], max(0, 1 - sum(q[-G])))    
  return(q[g])                              
}
```

Creating function for the sampler
```{r}
Bayes_LCR <- function(Y,X,initialsigma,target_accept = 0.234, G, n_iter, burn_in, adapt_interval, verbose = FALSE){
  p <- ncol(as.matrix(X)) #Getting the number of covariates as p
  #append 1 to X for \beta_0 coeff
  if (is.vector(X)){
    ones <- rep(1,length(X))
    X <- cbind(ones,X)
  } else{
    ones <- rep(1,nrow(X))
    X <- cbind(ones,X)
  }
  n <- nrow(as.matrix(Y)) #number of observations
  M <- ncol(as.matrix(Y)) #number of variables
  K <- apply(Y, 2, function(x) length(unique(x))) #Vector to indicate the number of categories in each variable
  alpha <- rep(1, max(K))  #alpha parameters for theta_{gj} dirichlet distributions
  theta <- array(0, dim = c(G, M, max(K)))  #Initialising theta 
  for (g in 1:G) { #generating a sample from theta_{gj} vectors for each g and j}
    for (j in 1:M) {
      theta[g, j, 1:K[j]] <- rdirichlet(1, alpha[1:K[j]])  
    }
  }
  beta <- array(rnorm((G-1)*(p+1),2,0.5),dim = c(G-1,p+1)) #Initialising beta
  z <- array(0, dim = c(n,G)) #Initialising z matrix
  S <- array(0, dim = c(M,G,max(K))) #Initialising S variable
  gamma_matrix <- array(0,dim = c(G,n)) #initialising matrix to store logistic regression probabilities
  for (g in 1:G){
    for (i in 1:n){
      gamma_matrix[g,i] <- gamma_vec(beta,g,X,i,G)
    }
  }
  #Initialising arrays to store samples
  beta_samples <- array(0,dim = c(G-1,p+1,n_iter))
  theta_samples <- array(0,dim = c(G, M, max(K),n_iter))
  w <- array(0,dim = c(n,G)) #Initialising w matrix
  for (i in 1:n) {
    for (g in 1:G) {
      p1 <- 1
      for (j in 1:M){
        for(k in 1:K[j]){
          p1 <- p1*theta[g,j,k]^(Y[i,j] == k) # calculating double product. 
        }
      }
      w[i,g] <- gamma_matrix[g,i]*p1 #Updating entries of w. 
    }
  }
  z_samples <- array(0, dim = c(n,G,n_iter))
  for (i in 1:n){
    z[i,] <- rmultinom(1,1,w[i,])
  }
  accept_count <- 0 #number of accepted samples in each batch
  total_proposals <- 0 #counter for proposals made in each batch
  cont_accept_count <- 0 #number of accepted samples overall
  cont_total_proposals <- 0 #number of total proposals counter
  #beta_proposals <- array(0, dim = c(G-1,p+1)) not sure whether i need this or not
  #Initialising covariance matrices for beta proposals
  sigma1 <- diag(initialsigma,G-1) 
  sigma2 <- diag(initialsigma,p+1)
  #setting acceptance rate and list to store values of acceptance rate
  r_accept <- 0
  r_accept_list <- c()
  count <- 0 #counter for loop
  while(count < n_iter){
    for (j in 1:M){
      for (g in 1:G){
        for (k in 1:K[j]){
          S[j,g,k] = sum((Y[,j] == k)*z[,g]) #Update values of S
        }
      }
    }  
    for (g in 1:G) { #generating a sample from theta_{gj} vectors for each g and j}
      for (j in 1:M) {
        theta[g, j, 1:K[j]] <- rdirichlet(1, alpha[1:K[j]] + S[j,g,1:K[j]])  
      }
    }
    theta_samples[,,,count] <- theta #Storing theta value
    for (g in 1:G){
      for (i in 1:n){
        gamma_matrix[g,i] <- gamma_vec(beta,g,X,i,G) #Updating gamma matrix values
      }
    }
    for (i in 1:n) { #Creating w_i vectors for each i and then generating z_i vectors from multinomial(w_i)
      for (g in 1:G) {
        p1 <- 1
        for (j in 1:M){
          for(k in 1:K[j]){
            p1 <- p1*theta[g,j,k]^(Y[i,j] == k) # calculating double product. 
          }
        }
        w[i,g] <- gamma_matrix[g,i]*p1 #Updating entries of w. 
      }
      z[i,] <- rmultinom(1,1,w[i,])
    }
    z_samples[,,count] <- z
    beta_proposals <- rmatnorm(M = beta, U = sigma1, V = sigma2)
    total_proposals <- total_proposals + 1
    cont_total_proposals <- cont_total_proposals + 1
    log_acc_arg <- 0
    for (g in 1:(G)){
      for (i in 1:n){
        log_acc_arg <- log_acc_arg + z[i,g]*(log(gamma_vec(beta_proposals,g,X,i,G)) - log(gamma_vec(beta,g,X,i,G)))
      }
    }
    acc_arg <- exp(log_acc_arg)
    print( paste("acceptance ratio is " ,acc_arg))
    if (is.na(acc_arg)){
      print(paste("Acceptance ratio is NaN, replacing with 0"))
      acc_arg <- 0
    }
    if(runif(1) <= min(1,acc_arg)){ #accept-reject step
      beta <- beta_proposals
      accept_count <- accept_count + 1
      cont_accept_count <- cont_accept_count + 1
      #print("Accepted")
    } else{
      #print("rejected")
    }
    beta_samples[,,count] <- beta
    if (count > 0 && count %% adapt_interval == 0) {
      r_accept <- accept_count / total_proposals  # Calculate acceptance rate
      r_accept_list <- c(r_accept_list,r_accept)
      if (verbose == TRUE){
        print( paste("Iteration" , count, " completed, batch acceptance rate is " ,r_accept, ", continuous acceptance rate is ", continuous_acceptance_rate))
      }
      delta <- min(0.01,count^(-(1/2)))
      if (r_accept < target_accept) {
          sigma1 <- sigma1 * (1-delta)  # Shrink the covariance matrices 
          sigma2 <- sigma2 * (1-delta)
          if(verbose == TRUE){
            print("shrink")
          }
      } else if (r_accept > target_accept){
           sigma1 <- sigma1 * (1+delta)  # Expand the covariance matrices 
           sigma2 <- sigma2 * (1+delta)
          if(verbose == TRUE){
            print("expand")
          }
      }
      accept_count <- 0 #reset the batch accept count and total proposal count
      total_proposals <- 0
    }
    count = count + 1 #increment the iteration count
    continuous_acceptance_rate <- cont_accept_count/cont_total_proposals
    #print(paste("Iteration ",count, " completed, acceptance rate is", continuous_acceptance_rate))
    #print(count)
  }
  beta_samples <- beta_samples[,,(burn_in+1):(n_iter-1), drop=FALSE]
  theta_samples <- theta_samples[,,,(burn_in+1):(n_iter-1), drop=FALSE]
  theta_estimate <- apply(theta_samples, c(1, 2, 3), mean)
  beta_estimate <- apply(beta_samples, c(1, 2), mean)
  beta_sd <- apply(beta_samples, c(1, 2), sd)
  theta_sd <- apply(theta_samples, c(1, 2, 3), sd)
  z_samples <- z_samples[,,(burn_in+1):(n_iter-1), drop=FALSE]
  x <- list(beta_samples = beta_samples,theta_samples = theta_samples,z_samples=z_samples,beta_estimate=beta_estimate,theta_estimate=theta_estimate,beta_sd=beta_sd,theta_sd=theta_sd)
  return(x)
}
```

Testing the sampler on a 2 group simulated data set with 4 manifest variables and 2 concomitant variables
```{r}

set.seed(123)

data <- poLCA.simdata(N = 500, probs = NULL, nclass = 2, ndv = 4, nresp = NULL, x = NULL, niv = 2, b =matrix(c(1.123,2.536,2.947),nrow = 3, ncol = 1), P = NULL, missval = FALSE, pctmiss = NULL)

Y <- cbind(data[["dat"]][["Y1"]], data[["dat"]][["Y2"]],data[["dat"]][["Y3"]],data[["dat"]][["Y4"]])
X <- cbind(data[["dat"]][["X1"]], data[["dat"]][["X2"]])

BLCR1 <- Bayes_LCR(Y,X,0.2,G = 2, n_iter = 100000, burn_in = 2000, adapt_interval = 50, verbose = TRUE)
```



Trace plots for $\beta$
```{r}
par(mfrow = c(3, 1))
for (i in 1:1) {
  for (j in 1:3) {
    values <- BLCR1$beta_samples[i,j,]
    plot(values, type = 'l', main = bquote("Trace plot for " ~ beta[.(i)][.(j)]), xlab = "Index", ylab = "Value")
  }
}
```


Density plots for $\beta$
```{r}
par(mfrow = c(3,1))
for (i in 1:1) {
  for (j in 1:3) {
    values <- BLCR1$beta_samples[i,j,]
    plot(density(values), main = bquote("Density plot for " ~ beta[.(i)][.(j)]), xlab = "Index", ylab = "Value")
    rug(jitter(values))
  }
}
```


Trying out a 3 group model with 2 covariates and 4 manifest variables
```{r}

data <- poLCA.simdata(N = 500, probs = NULL, nclass = 3, ndv = 4, nresp = NULL, x = NULL, niv = 2, b =matrix(c(1.123,2.536,2.947,3.89,9,15),nrow = 3, ncol = 2), P = NULL, missval = FALSE, pctmiss = NULL)

Y <- cbind(data[["dat"]][["Y1"]], data[["dat"]][["Y2"]],data[["dat"]][["Y3"]],data[["dat"]][["Y4"]])
X <- cbind(data[["dat"]][["X1"]], data[["dat"]][["X2"]])

BLCR2 <- Bayes_LCR(Y,X,0.2,G = 3, n_iter = 10000, burn_in = 2000, adapt_interval = 50, verbose = TRUE)
```



