---
title: "R Notebook"
output: html_notebook
---


Gonna try it with simulated data from poLCA dataset.

```{r}

library(poLCA)
library(MCMCpack)
library(BayesLCA)
library(matrixNormal)
```



Gonna try make a Gibbs Sampler to produce parameter esimates for latent class regression model
Ill try test it with the election data set from poLCA
```{r}

set.seed(123)
#Y <- cbind(data$MORALG, data$CARESG, data$KNOWG, data$LEADG, data$DISHONG, data$INTELG) #choosing the variables we wanna work with

#X <- data$PARTY
#num_X_columns <- ncol(X)  # Number of columns in the original X


#For the moment Im gonna remove observations containing NA values from both X and Y

#combined <- cbind(X, Y)
#combined_cleaned <- na.omit(combined)
#if (is.vector(X)) {
    # If X is a vector, extract the first column (X as a vector)
 #   X <- combined_cleaned[, 1]
    # Y would be the remaining columns (as a matrix or data frame)
 #   Y <- combined_cleaned[, 2:ncol(combined_cleaned)]
#} else {
    # If X is a matrix or data frame, determine the number of columns
#    num_X_columns <- ncol(X)
    # Extract X columns
 #   X <- combined_cleaned[, 1:num_X_columns]
 #   # Y will be the remaining columns
 #   Y <- combined_cleaned[, (num_X_columns + 1):ncol(combined_cleaned)]
#}

data <- poLCA.simdata(N = 5000, probs = NULL, nclass = 2, ndv = 4, nresp = NULL, x = NULL, niv = 2, b =matrix(c(1.123,2.536,2.947),nrow = 3, ncol = 1), P = NULL, missval = FALSE, pctmiss = NULL)

Y <- cbind(data[["dat"]][["Y1"]], data[["dat"]][["Y2"]],data[["dat"]][["Y3"]],data[["dat"]][["Y4"]])
X <- cbind(data[["dat"]][["X1"]], data[["dat"]][["X2"]])




p <- ncol(as.matrix(X)) #Getting the number of covariates as p
G <- 2 #number of latent classes


#append 1 to X for \beta_0 coeff
if (is.vector(X)){
  ones <- rep(1,length(X))
  X <- cbind(ones,X)
} else{
  ones <- rep(1,nrow(X))
  X <- cbind(ones,X)
}




n <- nrow(as.matrix(Y)) #number of observations
M <- ncol(as.matrix(Y)) #number of variables
K <- numeric(M) #Vector giving the categories for each variable
for (i in 1:M) {
  K[i] <- length(unique(Y[, i]))
}

alpha <- rep(1, max(K))  #alpha parameters for theta_{gj} dirichlet distributions

theta <- array(0, dim = c(G, M, max(K)))  #Initialising theta 


for (g in 1:G) { #generating a sample from theta_{gj vectors for each g and j}
  for (j in 1:M) {
    theta[g, j, 1:K[j]] <- rdirichlet(1, alpha[1:K[j]])  
  }
}

#creating beta matrix
beta <- array(rnorm(G*(p+1),2,0.5),dim = c(G,p+1))

#Creating function for multinomial logistic regression
gamma <- function(beta, g, x, i, G) {
  xi <- as.matrix(x)[i,]                       
  betaxi <- as.vector(beta %*% xi)             
  numerator <- exp(betaxi[g])                  
  denominator <- 1 + sum(exp(betaxi[-G]))      
  return(numerator / denominator)    
}


gamma_vec <- function(beta,g,x,i,G){
  q <- c()
  for (v in 1:(G-1)) {
    q <- c(q, gamma(beta, v, X, i, G))
  }
  s <- q
  q <- c(q, max(0, 1 - sum(s)))
  return(q[g])
}







w <- array(0,dim = c(n,G)) #Initialising w matrix




for (i in 1:n) {
  for (g in 1:G) {
    p1 <- 1
    for (j in 1:M){
      for(k in 1:K[j]){
        p1 <- p1*theta[g,j,k]^(Y[i,j] == k) # calculating double product. note dependence on theta and Y
      }
    }
    w[i,g] <- gamma_vec(beta,g,X,i,G)*p1 #Updating entries of w. note dependence on beta
  }
}



z <- array(0, dim = c(n,G)) #Initialising z matrix
for (i in 1:n){
  z[i,] <- rmultinom(1,1,w[i,])
}


#Now to update the parameter values
#starting with theta
#Creating the derived variables C and S
C <-array(0, dim = c(n,M,G,max(K)))
for (i in 1:n){
  for (j in 1:M){
    for (g in 1:G){
      for (k in 1:K[j]){
        C[i,j,g,k] <- (Y[i,j] == k)*(z[i,g])
      }
    }
  }
}

S <- array(0, dim = c(M,G,max(K))) 
for (j in 1:M){
  for (g in 1:G){
    for (k in 1:K[j])
      S[j,g,k] = sum(C[,j,g,k])
  }
}




#Now generating the updated theta sample

for (g in 1:G) { #generating a sample from theta_{gj vectors for each g and j}
  for (j in 1:M) {
    theta[g, j, 1:K[j]] <- rdirichlet(1, alpha[1:K[j]] + S[j,g,1:K[j]])  
  }
}



#Now the MH step for sampling beta parameters, unfinished
#--------------------------------------------------------





#now running in a loop, unfinished
n_iter <- 10000
count <- 0
burn_in <- 100
adapt_interval <- 50
epsilon <- 1e-10


beta_samples <- array(0,dim = c(G,p+1,n_iter))
theta_samples <- array(0,dim = c(G, M, max(K),n_iter))
z_samples <- array(0, dim = c(n,G,n_iter))


accept_count <- 0
total_proposals <- 0
target_accept <- 0.23


beta_proposals <- array(0, dim = c(G,p+1))




sigma1 <- diag(0.2,G)
sigma2 <- diag(0.2,p+1)
 


r_accept <- 0
C <- array(0, dim = c(n,M,G,max(K)))  
S <- array(0, dim = c(M,G,max(K)))    


while(count < n_iter){
  for (i in 1:n){
    for (j in 1:M){
      for (g in 1:G){
        for (k in 1:K[j]){
          C[i,j,g,k] <- (Y[i,j] == k)*(z[i,g])
        }
      } 
    }
  }
  for (j in 1:M){
    for (g in 1:G){
      for (k in 1:K[j]){
        S[j,g,k] <- sum(C[,j,g,k])
      }
    }
  }
  
  for (g in 1:G) { #generating a sample from theta_{gj} vectors for each g and j}
    for (j in 1:M) {
      theta[g, j, 1:K[j]] <- rdirichlet(1, alpha[1:K[j]] + S[j,g,1:K[j]])  
    }
  }
  theta_samples[,,,count] <- theta
  
  
  for (i in 1:n) { #Creating w_i vectors for each i and then generating z_i vectors from multinomial(w_i)
    for (g in 1:G) {
      p1 <- 1
      for (j in 1:M){
        for(k in 1:K[j]){
          p1 <- p1*theta[g,j,k]^(Y[i,j] == k) # calculating double product. note dependence on theta and Y
        }
      }
      w[i,g] <- gamma_vec(beta,g,X,i,G)*p1 #Updating entries of w. note dependence on beta
    }
    z[i,] <- rmultinom(1,1,w[i,])
  }
  
  z_samples[,,count] <- z
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #________________________________________________________
  beta_proposals <- rmatnorm(M = beta, U = sigma1, V = sigma2)
  total_proposals <- total_proposals + 1
  log_acc_arg <- 0
  for (g in 1:G){
    for (i in 1:n){
      log_acc_arg <- log_acc_arg + z[i,g]*(log(gamma_vec(beta_proposals,g,X,i,G)) - log(gamma_vec(beta,g,X,i,G)))
    }
  }
  acc_arg <- exp(log_acc_arg)
  print( paste("acceptance ratio is " ,acc_arg))
  if(runif(1) < min(1,acc_arg)){
      beta <- beta_proposals
      accept_count <- accept_count + 1
      print("Accepted")
    } else{
      print("rejected")
    }
  beta_samples[,,count] <- beta
  if (count > 0 && count %% adapt_interval == 0) {
      r_accept <- accept_count / total_proposals  # Calculate acceptance rate
      print( paste("acceptance rate is " ,r_accept))
      delta <- min(0.01,count^(-(1/2)))
      if (r_accept < target_accept) {
          sigma1 <- sigma1 * (1-delta)  # Shrink the covariance matrices 
          sigma2 <- sigma2 * (1-delta)
          print("shrink")
      } else if (r_accept > target_accept){
           sigma1 <- sigma1 * (1+delta)  # Expand the covariance matrices 
           sigma2 <- sigma2 * (1+delta)
        print("expand")
      }
    accept_count <- 0
    total_proposals <- 0
  }
  count = count + 1
  print(paste("Iteration ",count, " completed"))
}


```
