---
title: "LCR using probit augmentation (like Albert and Chib (1993))"
output: html_notebook
---

```{r}
library(ggplot2)
library(poLCA)
library(MCMCpack)
library(BayesLCA)
library(matrixNormal)
library(truncnorm)
```

```{r}

set.seed(123)


data <- poLCA.simdata(N = 5000, probs = NULL, nclass = 2, ndv = 4, nresp = NULL, x = NULL, niv = 2, b =matrix(c(3,5,7),nrow = 3, ncol = 1), P = NULL, missval = FALSE, pctmiss = NULL)


tc <- data[["trueclass"]]
tc[tc==1] <- 0
tc[tc==2] <- 1




Y <- cbind(data[["dat"]][["Y1"]], data[["dat"]][["Y2"]],data[["dat"]][["Y3"]],data[["dat"]][["Y4"]])
X <- cbind(data[["dat"]][["X1"]], data[["dat"]][["X2"]])

p <- ncol(as.matrix(X)) #Getting the number of covariates as p
G <- 2 #number of classes 

#append 1 to X for \beta_0 coeff
if (is.vector(X)){
  ones <- rep(1,length(X))
  X <- cbind(ones,X)
} else{
  ones <- rep(1,nrow(X))
  X <- cbind(ones,X)
}


data_probit_fit <- glm(tc ~ X1 + X2, data = data[["dat"]], family = binomial(link = "probit"))
true_beta <- data_probit_fit$coefficients


n <- nrow(as.matrix(Y)) #number of observations
M <- ncol(as.matrix(Y)) #number of variables
K <- apply(Y, 2, function(x) length(unique(x))) #Vector to indicate the number of categories in each variable


#Initialising variables---------------------------------------------------------


theta <- array(0, dim = c(G, M, max(K)))  #Initialising theta
alpha <- rep(1, max(K))  #alpha parameters for theta_{gj} dirichlet distributions

for (g in 1:G) { #generating a sample from theta_{gj vectors for each g and j}
  for (j in 1:M) {
    theta[g, j, 1:K[j]] <- rdirichlet(1, alpha[1:K[j]])  
  }
}


#creating beta matrix
beta <- array(rnorm((G-1)*(p+1),2,0.5),dim = c(G-1,p+1))

w <- array(0, dim = c(n,G)) #Initialising w matrix

z <- array(0, dim = c(n,G)) #initialising z matrix
for(i in 1:n){
  z[i,] <- rmultinom(1,1,c(0.5,0.5))
}

C <- array(0, dim = c(n,1))
for (i in 1:n){
  mu <-  beta %*% X[i,]
  C[i] <- (all(z[i,] == c(1,0)))*rtruncnorm(1,a=0,b=Inf,mean = mu,sd=1) + (all(z[i,] == c(0,1)))*rtruncnorm(1,a=-Inf,b=0,mean = mu,sd=1)
}

#beta <- mvrnorm(1,mu = (solve(t(X)%*%X))%*%(t(X)%*%C), Sigma = solve(t(X)%*%X))
beta <- c(1.833160,2.852735,4.016850)

n_iter <- 100000
burnin <- 5000
thin <- 10
beta_samples <- array(0,dim = c(G-1,p+1,n_iter))
z_samples <- array(0, dim = c(n,g,n_iter))
C_samples <- array(0,dim = c(n,1,n_iter))
theta_samples <- array(0, dim = c(G,M,max(K),n_iter))

count <- 1



#Running the loop---------------------------------------------------------------

while (count<n_iter){
  S <- array(0, dim = c(M,G,max(K)))
  for (j in 1:M){
    for (g in 1:G){
      for (k in 1:K[j]){
        S[j,g,k] = sum((Y[,j] == k)*z[,g])
      }
    }
  }
  for (g in 1:G) { #generating a sample from theta_{gj} vectors for each g and j}
    for (j in 1:M) {
      theta[g, j, 1:K[j]] <- rdirichlet(1, alpha[1:K[j]] + S[j,g,1:K[j]])  
    }
  }
  theta_samples[,,,count] <- theta
  
  
  for (i in 1:n){
    I1 <- pnorm(beta %*% X[i,])
    I0 <- (1-I1)
    p1 <- 1
    p0 <- 1
    for(j in 1:M){
      for(k in 1:K[j]){
        p1<- p1*theta[1,j,k]^(Y[i,j] == k)
        p0<- p0*theta[2,j,k]^(Y[i,j] == k)
      }
    }
    w[i, ] <- c(I1*p1,I0*p0)
    z[i,] <- rmultinom(1,1,w[i,])
  }
  z_samples[,,count] <- z
  
  
  for (i in 1:n){
    mu <-  beta %*% X[i,]
    C[i] <- (all(z[i,] == c(1,0)))*rtruncnorm(1,a=0,b=Inf,mean = mu,sd=1) + all((z[i,] == c(0,1)))*rtruncnorm(1,a=-Inf,b=0,mean = mu,sd=1)
  }
  
  C_samples[,,count] <- C
  
  beta <- mvrnorm(1,mu = (solve(t(X)%*%X))%*%(t(X)%*%C), Sigma = solve(t(X)%*%X))
  beta_samples[,,count] <- beta
  if(count %% 100 == 0){
    print(paste("iteration ", count, "completed"))
  }
  count <- count + 1
}

beta_samples_burned <- beta_samples[,,burnin:(n_iter-1), drop = FALSE]
theta_samples_burned <- theta_samples[,,,burnin:(n_iter-1), drop = FALSE]
C_samples_burned <- C_samples[,,burnin:(n_iter-1), drop = FALSE]
z_samples_burned <- z_samples[,,burnin:(n_iter-1), drop = FALSE]

beta_samples_thin <- beta_samples_burned[,,seq(1, dim(beta_samples_burned)[3], by = thin), drop = FALSE]
theta_samples_thin <- theta_samples_burned[,,,seq(1, dim(theta_samples_burned)[4], by = thin), drop = FALSE]
C_samples_thin <- C_samples_burned[,,seq(1, dim(C_samples_burned)[2], by = thin), drop = FALSE]
z_samples_thin <- z_samples[,,seq(1, dim(z_samples_burned)[3], by = thin), drop = FALSE]

beta_estimate <- apply(beta_samples_thin, c(1,2), mean)
beta_sd <- apply(beta_samples_thin, c(1,2), sd)
theta_estimate <- apply(theta_samples_thin, c(1,2,3), mean)
theta_sd <- apply(theta_samples_thin, c(1,2), sd)


```


Parameter Estimates
```{r}
paste("True value of Beta: ", paste(c(3,5,7), collapse = ", "))
paste("beta estimate: ", paste(beta_estimate, collapse = ", "))

#True value of beta paramter is (3,5,7), so theres something likely wrong here
truetheta <-  data[["probs"]]
cat("True value of theta:\n", paste(lapply(truetheta, function(x) paste(capture.output(print(x)), collapse = "\n")), collapse = "\n\n"))

#Going to change the layout of the theta so it looks like the true theta in order to compare
theta_estimate1 <- list()
for (j in 1:M){
  theta_estimate1[[j]] <-matrix(0, ncol = K[j], nrow = G)
  for (k in 1:K[j]){
    for (g in 1:G){
      theta_estimate1[[j]][g,k] <- theta_estimate[g,j,k]
    }
  }
}

cat("theta estimate:\n", paste(lapply(theta_estimate1, function(x) paste(capture.output(print(x)), collapse = "\n")), collapse = "\n\n"))
```



Testing out the prediction accuracy
```{r}
class_estimate_vec <- c()
class_estimate_vec_truebeta <- c()
class_vec <- c()
class_vec1 <- c()
class_vec_truebeta <- c()
class_vec_truebeta1 <- c()
for (i in 1:n){
  class_estimate <- pnorm(as.vector(X[i,])%*%as.vector(beta_estimate))
  class_estimate_truebeta <- pnorm(as.vector(X[i,])%*%as.vector(true_beta))
  class_estimate_vec <- c(class_estimate_vec,class_estimate)
  class_estimate_vec_truebeta <- c(class_estimate_truebeta,class_estimate_truebeta)
  class_vec <- c(class_vec, rbinom(1,1,class_estimate))
  class_vec_truebeta <- c(class_vec_truebeta,rbinom(1,1,class_estimate_truebeta))
  if (class_estimate>=0.5){
    class_vec1 <- c(class_vec1, 1)
  } else {
    class_vec1 <- c(class_vec1, 0)
  }
  if (class_estimate_truebeta>=0.5){
    class_vec_truebeta1 <- c(class_vec_truebeta1, 1)
  } else {
    class_vec_truebeta1 <- c(class_vec_truebeta1, 0)
  }
}

class_vec[class_vec==1] <- 2
class_vec[class_vec==0] <- 1
class_vec1[class_vec1==1] <- 2
class_vec1[class_vec1==0] <- 1

class_vec_truebeta[class_vec_truebeta==1] <- 2
class_vec_truebeta[class_vec_truebeta==0] <- 1
class_vec_truebeta1[class_vec_truebeta1==1] <- 2
class_vec_truebeta1[class_vec_truebeta1==0] <- 1

proportion_agreement_binom_truebeta <- mean(class_vec_truebeta == data[["trueclass"]])
proportion_agreement_threshold_truebeta <- mean(class_vec_truebeta1 == data[["trueclass"]])

proportion_agreement_binom <- mean(class_vec == data[["trueclass"]])
proportion_agreement_threshold <- mean(class_vec1 == data[["trueclass"]])

```



F1 test
```{r}

class_vec[class_vec == 2] <- 0
dat_1 <- data[["trueclass"]]
dat_1[dat_1 == 2] <- 0
TP <- sum((dat_1 == 1) & (class_vec == 1))
FP <- sum((dat_1 == 0) & (class_vec == 1))
FN <- sum((dat_1 == 1) & (class_vec == 0))

precision <- TP / (TP + FP)
recall <- TP / (TP + FN)

f1_score <- 2 * ((precision * recall) / (precision + recall))
```

running F1 test on true beta value
```{r}


class_vec_truebeta[class_vec_truebeta == 2] <- 0
dat_1 <- data[["trueclass"]]
dat_1[dat_1 == 2] <- 0
TP <- sum((dat_1 == 1) & (class_vec_truebeta == 1))
FP <- sum((dat_1 == 0) & (class_vec_truebeta == 1))
FN <- sum((dat_1 == 1) & (class_vec_truebeta == 0))

precision <- TP / (TP + FP)
recall <- TP / (TP + FN)

f1_score_truebeta <- 2 * ((precision * recall) / (precision + recall))

```


Plotting P(1) against X1, holding X2 constant
```{r}

X2_mean <- mean(data[["dat"]][["X2"]])
x_vals <- seq(-3,3,0.001)
CI_upper <- beta_estimate + 1.96*beta_sd
CI_lower <- beta_estimate - 1.96*beta_sd
plot(x_vals,pnorm(beta_estimate[1] + beta_estimate[2]*x_vals + beta_estimate[3]*X2_mean, 0,1),type = "l" )
lines(y_vals,pnorm(true_beta[1]+true_beta[2]*y_vals +true_beta[3]*X2_mean,0,1), col = "blue")
points(data[["dat"]][["X1"]], class_vec, col = "red", pch = 19)


```


Plotting P(1) against X2
```{r}


X1_mean <- mean(data[["dat"]][["X1"]])
y_vals <- seq(-3,3,0.001)
plot(y_vals,pnorm(beta_estimate[1] + beta_estimate[2]*X1_mean + beta_estimate[3]*y_vals, 0,1),type = "l" )
lines(y_vals,pnorm(true_beta[1]+true_beta[2]*X1_mean +true_beta[3]*y_vals,0,1), col = "blue")
points(data[["dat"]][["X2"]], class_vec, col = "red", pch = 19)


```









