---
title: "LCR using probit augmentation (like Albert and Chib (1993))"
output: html_notebook
---

```{r}
library(poLCA)
library(MCMCpack)
library(BayesLCA)
library(matrixNormal)
library(truncnorm)
```


```{r}

set.seed(123)


data <- poLCA.simdata(N = 500, probs = NULL, nclass = 2, ndv = 4, nresp = NULL, x = NULL, niv = 2, b =matrix(c(3,5,7),nrow = 3, ncol = 1), P = NULL, missval = FALSE, pctmiss = NULL)

Y <- cbind(data[["dat"]][["Y1"]], data[["dat"]][["Y2"]],data[["dat"]][["Y3"]],data[["dat"]][["Y4"]])
X <- cbind(data[["dat"]][["X1"]], data[["dat"]][["X2"]])

p <- ncol(as.matrix(X)) #Getting the number of covariates as p
G <- 2 #number of classes 

#append 1 to X for \beta_0 coeff
if (is.vector(X)){
  ones <- rep(1,length(X))
  X <- cbind(ones,X)
} else{
  ones <- rep(1,nrow(X))
  X <- cbind(ones,X)
}

n <- nrow(as.matrix(Y)) #number of observations
M <- ncol(as.matrix(Y)) #number of variables
K <- apply(Y, 2, function(x) length(unique(x))) #Vector to indicate the number of categories in each variable


#Initialising variables---------------------------------------------------------


theta <- array(0, dim = c(G, M, max(K)))  #Initialising theta
alpha <- rep(1, max(K))  #alpha parameters for theta_{gj} dirichlet distributions

for (g in 1:G) { #generating a sample from theta_{gj vectors for each g and j}
  for (j in 1:M) {
    theta[g, j, 1:K[j]] <- rdirichlet(1, alpha[1:K[j]])  
  }
}


#creating beta matrix
beta <- array(rnorm((G-1)*(p+1),2,0.5),dim = c(G-1,p+1))

w <- array(0, dim = c(n,G)) #Initialising w matrix

z <- array(0, dim = c(n,G)) #initialising z matrix
for(i in 1:n){
  z[i,] <- rmultinom(1,1,c(0.5,0.5))
}

C <- array(0, dim = c(n,1))
for (i in 1:n){
  mu <-  beta %*% X[i,]
  C[i] <- (all(z[i,] == c(1,0)))*rtruncnorm(1,a=0,b=Inf,mean = mu,sd=1) + (all(z[i,] == c(0,1)))*rtruncnorm(1,a=-Inf,b=0,mean = mu,sd=1)
}

beta <- mvrnorm(1,mu = (solve(t(X)%*%X))%*%(t(X)%*%C), Sigma = solve(t(X)%*%X))


n_iter <- 100000
burnin <- 5000
thin <- 10
beta_samples <- array(0,dim = c(G-1,p+1,n_iter))
z_samples <- array(0, dim = c(n,g,n_iter))
C_samples <- array(0,dim = c(n,1,n_iter))
theta_samples <- array(0, dim = c(G,M,max(K),n_iter))

count <- 1



#Running the loop---------------------------------------------------------------

while (count<n_iter){
  S <- array(0, dim = c(M,G,max(K)))
  for (j in 1:M){
    for (g in 1:G){
      for (k in 1:K[j]){
        S[j,g,k] = sum((Y[,j] == k)*z[,g])
      }
    }
  }
  for (g in 1:G) { #generating a sample from theta_{gj} vectors for each g and j}
    for (j in 1:M) {
      theta[g, j, 1:K[j]] <- rdirichlet(1, alpha[1:K[j]] + S[j,g,1:K[j]])  
    }
  }
  theta_samples[,,,count] <- theta
  
  
  for (i in 1:n){
    I1 <- (C[i]>0)*pnorm(beta %*% X[i,])
    I0 <- (C[i]<=0)*(1-I1)
    p1 <- 1
    p0 <- 1
    for(j in 1:M){
      for(k in 1:K[j]){
        p1<- p1*theta[1,j,k]^(Y[i,j] == k)
        p0<- p0*theta[2,j,k]^(Y[i,j] == k)
      }
    }
    w[i, ] <- c(I1*p1,I0*p0)
    z[i,] <- rmultinom(1,1,w[i,])
  }
  z_samples[,,count] <- z
  
  
  for (i in 1:n){
    mu <-  beta %*% X[i,]
    C[i] <- (all(z[i,] == c(1,0)))*rtruncnorm(1,a=0,b=Inf,mean = mu,sd=1) + all((z[i,] == c(0,1)))*rtruncnorm(1,a=-Inf,b=0,mean = mu,sd=1)
  }
  
  C_samples[,,count] <- C
  
  beta <- mvrnorm(1,mu = (solve(t(X)%*%X))%*%(t(X)%*%C), Sigma = solve(t(X)%*%X))
  beta_samples[,,count] <- beta
  if(count %% 100 == 0){
    print(paste("iteration ", count, "completed"))
  }
  count <- count + 1
}

beta_samples_burned <- beta_samples[,,burnin:(n_iter-1), drop = FALSE]
theta_samples_burned <- theta_samples[,,,burnin:(n_iter-1), drop = FALSE]
C_samples_burned <- C_samples[,,burnin:(n_iter-1), drop = FALSE]
z_samples_burned <- z_samples[,,burnin:(n_iter-1), drop = FALSE]

beta_samples_thin <- beta_samples_burned[,,seq(1, dim(beta_samples_burned)[3], by = thin), drop = FALSE]
theta_samples_thin <- theta_samples_burned[,,,seq(1, dim(theta_samples_burned)[4], by = thin), drop = FALSE]
C_samples_thin <- C_samples_burned[,,seq(1, dim(C_samples_burned)[2], by = thin), drop = FALSE]
z_samples_thin <- z_samples[,,seq(1, dim(z_samples_burned)[3], by = thin), drop = FALSE]

beta_estimate <- apply(beta_samples_thin, c(1,2), mean)
theta_estimate <- apply(theta_samples_thin, c(1,2,3), mean)


```

Parameter Estimates
```{r}
paste("True value of Beta: ", paste(c(3,5,7), collapse = ", "))
paste("beta estimate: ", paste(beta_estimate, collapse = ", "))

#True value of beta paramter is (3,5,7), so theres something likely wrong here
truetheta <-  data[["probs"]]
cat("True value of theta:\n", paste(lapply(truetheta, function(x) paste(capture.output(print(x)), collapse = "\n")), collapse = "\n\n"))

#Going to change the layout of the theta so it looks like the true theta in order to compare
theta_estimate1 <- list()
for (j in 1:M){
  theta_estimate1[[j]] <-matrix(0, ncol = K[j], nrow = G)
  for (k in 1:K[j]){
    for (g in 1:G){
      theta_estimate1[[j]][g,k] <- theta_estimate[g,j,k]
    }
  }
}

cat("theta estimate:\n", paste(lapply(theta_estimate1, function(x) paste(capture.output(print(x)), collapse = "\n")), collapse = "\n\n"))



```


Trace plots for $\beta$
```{r}
par(mfrow = c(3, 1), mar = c(2,2,2,2))
for (i in 1:1) {
  for (j in 1:3) {
    values <- beta_samples_thin[i,j,]
    plot(values, type = 'l', main = bquote("Trace plot for " ~ beta[.(i)][.(j)]),
         xlab = "Index", ylab = "Value")
  }
}
```



Density plots for $\beta$
```{r}
par(mfrow = c(3,1),mar = c(2,2,2,2))
for (i in 1:1) {
  for (j in 1:3) {
    values <- beta_samples_thin[i,j,]
    plot(density(values), main = bquote("Density plot for " ~ beta[.(i)][.(j)]),
         xlab = "Index", ylab = "Value")
    rug(jitter(values))
  }
}
```


