---
title: "BLCR Probit Working"
output: html_notebook
---

```{r}
library(ggplot2)
library(tidyr)
library(poLCA)
library(MCMCpack)
library(BayesLCA)
library(matrixNormal)
library(truncnorm)
library(profvis)
library(Rcpp)
source("./functions_for_modular_code_probit_BLCR.R")
source("./generate_BLCR_probit_binary.R")
#sourceCpp("BLCR/BLCR_probit/S_update.cpp")

```

```{r}

seed <- 123

#theta1 <- matrix(c(0.8,0.2,0.2,0.8), nrow = 2, byrow = TRUE)
#theta3 <- matrix(c(0.2,0.8,0.8,0.2), nrow = 2, byrow = TRUE)
#theta2 <- theta1
#theta4 <- theta3

theta1 <- matrix(c(0.8,0.2,0.2,0.8), nrow = 2, byrow = TRUE)
#theta1 <- matrix(c(0.8,0.2,0.2,0.2,0.5,0.3), nrow = 2, byrow = TRUE)
theta3 <- matrix(c(0.2,0.8,0.8,0.2), nrow = 2, byrow = TRUE)
theta2 <- theta1
#theta2 <- matrix(c(0.4,0.3,0.2,0.1,0.2,0.4,0.3,0.1), nrow = 2, byrow = TRUE)
theta4 <- theta3
theta <- list(theta1,theta2,theta3,theta4)


data <- prepare_data_2group_poLCA_covariates(seed, n = 1000, M = 4, p = 2, beta = c(1,3,-2), theta = theta)

X <- data$X
Y <- data$Y

#init <- initialize_variables_2group_BLCR(X,Y)

fit1 <- run_gibbs_BLCR_2class(Y,X,n_iter = 10000, burnin = 1000, verbose = TRUE)





```

```{r}

fit2 <- glm(data$tc ~ data$X[,1] + data$X[,2], family = binomial(link = probit))
glm_coeffs <- fit2$coefficients
plot(fit1$beta_samples[1,1,], type = 'l')
plot(fit1$beta_samples[1,2,], type = 'l')
plot(fit1$beta_samples[1,3,], type = 'l')

```



```{r}
beta_mcmc <- as.mcmc(fit1$beta_samples[1,,])

theta11_mcmc <- as.mcmc(fit1$theta_samples[1,1,,])
theta21_mcmc <- as.mcmc(fit1$theta_samples[2,1,,])
theta12_mcmc <- as.mcmc(fit1$theta_samples[1,2,,])
theta22_mcmc <- as.mcmc(fit1$theta_samples[2,2,,])
theta13_mcmc <- as.mcmc(fit1$theta_samples[1,3,,])
theta23_mcmc <- as.mcmc(fit1$theta_samples[2,3,,])
theta14_mcmc <- as.mcmc(fit1$theta_samples[1,4,,])
theta24_mcmc <- as.mcmc(fit1$theta_samples[2,3,,])




theta11_mcmc_df <- data.frame( x = 1:500, theta111 = theta11_mcmc[1, 1:1000], theta112 = theta11_mcmc[2, 1:1000], theta113 = theta11_mcmc[3,1:1000])
theta11_mcmc_long <- theta11_mcmc_df %>% pivot_longer(cols = starts_with("theta"), names_to = "line", values_to = "value")
ggplot(theta11_mcmc_long, aes(x = x, y = value, color = line)) + geom_line() + scale_color_manual(values = c("red", "blue", "green")) + labs(title = "theta_11 plots", x = "Index", y = "Theta Values") + theme_minimal()

densityplot(beta_mcmc[1,])
densityplot(beta_mcmc[2,])
densityplot(beta_mcmc[3,])


truetheta <-  data[["data"]][["probs"]]
theta_estimate <- fit1$theta_estimate
cat("True value of theta:\n", paste(lapply(truetheta, function(x) paste(capture.output(print(x)), collapse = "\n")), collapse = "\n\n"))

#Going to change the layout of the theta so it looks like the true theta in order to compare
theta_estimate1 <- list()
for (j in 1:M){
  theta_estimate1[[j]] <-matrix(0, ncol = K[j], nrow = G)
  for (k in 1:K[j]){
    for (g in 1:G){
      theta_estimate1[[j]][g,k] <- theta_estimate[g,j,k]
    }
  }
}

cat("theta estimate:\n", paste(lapply(theta_estimate1, function(x) paste(capture.output(print(x)), collapse = "\n")), collapse = "\n\n"))

```