---
title: "R Notebook"
output: html_notebook
---


```{r}

library(BayesLogit)
library(Matrix)
source('./functions_for_varsel.R')

```

Simulating some logit data 

```{r}
p <- 3
n <- 1000
G <- 2
x1 <- rnorm(n)
x2 <- rnorm(n,-2,1)
x3 <- x2 + rnorm(n,0,0.1)
#Sigma1 <- matrix(c(1,0.3,0.3,1), nrow = 2, byrow = TRUE)
#mu1 <- c(2,3)
#x2_x3 <- mvrnorm(n,mu1,Sigma1)
#x4 <- rnorm(n,-2,1)
#x5 <- rnorm(n,0.5,2)
X <- cbind(1,x1,x2,x3)

truebeta <- cbind(matrix(c(1,0,1,2), ncol = 1),0) 

truemu <- X%*%truebeta

exp_truemu <- exp(truemu)

trueprobs <- exp_truemu/(rowSums(exp_truemu))

trueclass <- apply(trueprobs, 1, function(p) sample(seq_along(p), 1, prob = p))

Y <- trueclass


```



```{r}
#Initialisation

beta_prior_cov <- diag(p+1)

beta_prior_precision <- chol2inv(chol(beta_prior_cov))

beta_prior_mean <- rep(0, p+1)

beta <- cbind(matrix(rnorm(p+1), ncol = 1),0)

gamma <- rep(1,p+1)

kappa <- Y - 1/2

#update

#omega update

mu <- X%*%beta

omega <- rpg(n,1,mu[-G])

Omega <- diag(omega)

#beta update

beta_precision <- t(X)%*%Omega%*%X + beta_prior_precision

beta_cov <- chol2inv(chol(beta_precision))

beta_mean <- beta_cov%*%(t(X)%*%kappa + beta_prior_precision%*%beta_prior_mean)

beta <- cbind(mvrnorm(n=1,mu = beta_mean, Sigma = beta_cov),0)

#Metropolis step for gamma

gamma_prop_index <- sample(2:(p+1), 1)

gamma_prop <- gamma

if(gamma[gamma_prop_index] == 1){
  gamma_prop[gamma_prop_index] <- 0 
} else {
  gamma_prop[gamma_prop_index] <- 1
}

X_current <- X[,gamma == 1, drop = FALSE]
  
X_prop <- X[,gamma_prop == 1, drop = FALSE]

beta_prior_precision_prop <- beta_prior_precision[gamma_prop == 1,gamma_prop == 1, drop = FALSE]

beta_prior_precision_current <- beta_prior_precision[gamma == 1,gamma == 1, drop = FALSE]

beta_prior_mean_prop <- beta_prior_mean[gamma_prop == 1]

beta_prior_mean_current <- beta_prior_mean[gamma == 1]

beta_precision_prop <-  t(X_prop)%*%Omega%*%X_prop + beta_prior_precision_prop

beta_precision_current <-  t(X_current)%*%Omega%*%X_current + beta_prior_precision_current

beta_cov_prop <- chol2inv(chol(beta_precision_prop))

beta_cov_current <- chol2inv(chol(beta_precision_current))

beta_mean_prop <- beta_cov_prop%*%(t(X_prop)%*%kappa + beta_prior_precision_prop%*%beta_prior_mean_prop)

beta_mean_current <- beta_cov_current%*%(t(X_current)%*%kappa + beta_prior_precision_current%*%beta_prior_mean_current)

det_cov_prop <- det(beta_cov_prop)

det_cov_current <- det(beta_cov_current)

log_det_current <- log(det_cov_current)

log_det_prop <- log(det_cov_prop)

log_accept_ratio <- (1/2)*(t(beta_mean_prop)%*%(beta_precision_prop%*%beta_mean_prop) - t(beta_mean_current)%*%(beta_precision_current%*%beta_mean_current) + log_det_prop - log_det_current)

accept_ratio <- exp(log_accept_ratio)

if (runif(1) <= min(1,accept_ratio)){
  gamma <- gamma_prop
}

```
Running in a loop

```{r}

n_iter <- 1000

beta_samples <- matrix(0,nrow = length(beta), ncol = n_iter)

omega_samples <- matrix(0, nrow = length(omega), ncol = n_iter)

gamma_samples <- matrix(0, nrow = length(gamma), ncol = n_iter)

for (count in 1:n_iter){
  
  mu <- X%*%beta

  omega <- rpg(n,1,mu[-G])

  Omega <- diag(omega)

  #beta update

  beta_precision <- t(X)%*%Omega%*%X + beta_prior_precision
  
  beta_cov <- chol2inv(chol(beta_precision))

  beta_mean <- beta_cov%*%(t(X)%*%kappa + beta_prior_precision%*%beta_prior_mean)

  beta <- cbind(mvrnorm(n=1,mu = beta_mean, Sigma = beta_cov),0)

  #Metropolis step for gamma

  gamma_prop_index <- sample(2:(p+1), 1)

  gamma_prop <- gamma

  if(gamma[gamma_prop_index] == 1){
    gamma_prop[gamma_prop_index] <- 0 
  } else {
    gamma_prop[gamma_prop_index] <- 1
  }

  X_current <- X[,gamma == 1, drop = FALSE]
  
  X_prop <- X[,gamma_prop == 1, drop = FALSE]

  beta_prior_precision_prop <- beta_prior_precision[gamma_prop == 1,gamma_prop == 1, drop = FALSE]

  beta_prior_precision_current <- beta_prior_precision[gamma == 1,gamma == 1, drop = FALSE]

  beta_prior_mean_prop <- beta_prior_mean[gamma_prop == 1]

  beta_prior_mean_current <- beta_prior_mean[gamma == 1]

  beta_precision_prop <-  t(X_prop)%*%Omega%*%X_prop + beta_prior_precision_prop

  beta_precision_current <-  t(X_current)%*%Omega%*%X_current + beta_prior_precision_current

  beta_cov_prop <- chol2inv(chol(beta_precision_prop))

  beta_cov_current <- chol2inv(chol(beta_precision_current))

  beta_mean_prop <- beta_cov_prop%*%(t(X_prop)%*%kappa + beta_prior_precision_prop%*%beta_prior_mean_prop)

  beta_mean_current <- beta_cov_current%*%(t(X_current)%*%kappa + beta_prior_precision_current%*%beta_prior_mean_current)

  det_cov_prop <- det(beta_cov_prop)

  det_cov_current <- det(beta_cov_current)

  log_det_current <- log(det_cov_current)

  log_det_prop <- log(det_cov_prop)

  log_accept_ratio <- (1/2)*(t(beta_mean_prop)%*%(beta_precision_prop%*%beta_mean_prop) - t(beta_mean_current)%*%(beta_precision_current%*%beta_mean_current) + log_det_prop - log_det_current)

  accept_ratio <- exp(log_accept_ratio)

  if (runif(1) <= min(1,accept_ratio)){
    gamma <- gamma_prop
  }

  gamma_samples[,count] <- gamma
  beta_samples[,count] <- beta
  omega_samples[,count] <- omega
  
  
  print(accept_ratio)
  print(count)
}

```


Now trying the multinomial case - first simulating some data
```{r}

p <- 2
n <- 1000
G <- 3
x1 <- rnorm(n)
x2 <- rnorm(n)

#Sigma1 <- matrix(c(1,0.3,0.3,1), nrow = 2, byrow = TRUE)
#mu1 <- c(2,3)
#x2_x3 <- mvrnorm(n,mu1,Sigma1)
#x4 <- rnorm(n,-2,1)
#x5 <- rnorm(n,0.5,2)
X <- cbind(1,x1,x2)

real_beta <- cbind(matrix(c(1,2,2,-2,-2,1), ncol = G-1),0) 

real_mu <- X%*%real_beta

exp_real_mu <- exp(real_mu)

trueprobs <- exp_real_mu/(rowSums(exp_real_mu))

trueclass <- apply(trueprobs, 1, function(p) sample(seq_along(p), 1, prob = p))

Y <- trueclass

```



```{r}
#initialisation
X <- cbind(x1,x2)
#adding in a noise variable
X <- cbind(X,rnorm(n),rnorm(n),rnorm(n),rnorm(n)) 
Y <- trueclass-1
init <- PG_varsel_mult_init(X = X, Y = Y)
list2env(init, envir = .GlobalEnv)

#update
mu <- mu_update(X = X, beta = beta)
eta <- eta_update(mu = mu, C = C)
kappa <- kappa_update(z = z)
#beta_cov_up <- beta_cov_mean_update(Omega = Omega, beta_prior_cov = beta_prior_cov, beta_prior_mean = beta_prior_mean, kappa = kappa, C = C, X = X, G = G, beta_prior_cov_inv = beta_prior_cov_inv, beta_cov_inv = beta_cov_inv, beta_cov_inv_chol = beta_cov_inv_chol, beta_cov = beta_cov, beta_mean = beta_mean)
#list2env(beta_cov_up, envir = .GlobalEnv)
#beta <- beta_update(beta_mean = beta_mean, beta_cov = beta_cov, G = G, beta = beta)
exp_mu <- exp(mu)
C <- C_update(mu = mu, exp_mu = exp_mu, G = G, C = C)
omega_up <- omega_update(eta = eta, mu = mu, G = G, n = n, omega = omega, Omega = Omega)
list2env(omega_up, envir = .GlobalEnv)
gamma_up <- gamma_update(gamma = gamma, p = p, beta_prior_cov_inv = beta_prior_cov_inv, beta_prior_mean = beta_prior_mean, kappa = kappa , G = G, X_current = X_current, tau = tau)
list2env(gamma_up, envir = .GlobalEnv)
beta <- beta_update(gamma = gamma, X_current = X_current, G = G, p = p)
print(gamma)
print(beta)

```


Putting it in a loop
```{r}

#initialisation
X <- cbind(x1,x2)
#adding in a noise variable
X <- cbind(X,rnorm(n)) 
Y <- trueclass
init <- PG_varsel_mult_init(X = X, Y = Y)
list2env(init, envir = .GlobalEnv)

#hyperparameters for tau probability
a <- 1
b <- 1
  
  
n_iter <- 10000
beta_samples <- array(0, dim = c(dim(beta),n_iter))
gamma_samples <- array(0,dim = c(length(gamma),n_iter))
omega_samples <- array(0, dim = c(dim(omega),n_iter))
tau_samples <- numeric(n_iter)

for(count in 1:n_iter){
  mu <- mu_update(X = X, beta = beta)
  eta <- eta_update(mu = mu, C = C)
  kappa <- kappa_update(z = z)
#beta_cov_up <- beta_cov_mean_update(Omega = Omega, beta_prior_cov = beta_prior_cov, beta_prior_mean = beta_prior_mean, kappa = kappa, C = C, X = X, G = G, beta_prior_cov_inv = beta_prior_cov_inv, beta_cov_inv = beta_cov_inv, beta_cov_inv_chol = beta_cov_inv_chol, beta_cov = beta_cov, beta_mean = beta_mean)
#list2env(beta_cov_up, envir = .GlobalEnv)
#beta <- beta_update(beta_mean = beta_mean, beta_cov = beta_cov, G = G, beta = beta)
  exp_mu <- exp(mu)
  C <- C_update(mu = mu, exp_mu = exp_mu, G = G, C = C)
  omega_up <- omega_update(eta = eta, mu = mu, G = G, n = n, omega = omega, Omega = Omega)
  list2env(omega_up, envir = .GlobalEnv)
  gamma_up <- gamma_update(gamma = gamma, p = p, beta_prior_cov_inv = beta_prior_cov_inv, beta_prior_mean = beta_prior_mean, kappa = kappa , G = G, X_current = X_current, tau = tau)
  list2env(gamma_up, envir = .GlobalEnv)
  
  tau <- tau_update(gamma,a,b) 
  
  beta <- beta_update(gamma = gamma, X_current = X_current, G = G, p = p)

  beta_samples[,,count] <- beta

  gamma_samples[,count] <- gamma

  omega_samples[,,count] <- omega
  
  tau_samples[count] <- tau

  if (count %% 500 == 0){
    print(paste( 'Iteration ', count, ' completed.'))
  }
}

```






