---
title: "Latent Class Regression Gibbs Sampler with Pólya-Gamma Augmentation"
output: html_notebook
---

```{r}

library(poLCA)
library(BayesLogit)
library(MCMCpack)
library(nnet)
source("./functions_for_polya_gamma_BLCR.R")
setwd('..')
source('./LCR_sim_data.R')


```


```{r}
G <- 3
p <- 1
M <- 4
n <- 1000
#theta1 <- matrix(c(0.8,0.2,0.2,0.8, 0.3,0.7), nrow = G, byrow = TRUE)
theta1 <- matrix(c(0.8,0.2,0.3,0.7,0.2,0.8), nrow = G, byrow = TRUE)
theta3 <- matrix(c(0.7,0.3,0.4,0.6,0.2,0.8), nrow = G, byrow = TRUE)
theta2 <- matrix(c(0.9,0.1,0.5,0.5,0.1,0.9), nrow = G, byrow = TRUE)
theta4 <- matrix(c(0.6,0.4,0.3,0.7,0.8,0.2), nrow = G, byrow = TRUE)
#theta2 <- matrix(c(0.4,0.3,0.2,0.1,0.2,0.4,0.3,0.1), nrow = 2, byrow = TRUE)
real_theta <- list(theta1,theta2,theta3,theta4)
real_beta <- matrix(c(-1,1,-1,1), nrow = p+1, ncol = G-1, byrow = TRUE)
data <- LCR_sim_data(theta = real_theta, beta = real_beta, n_samples = n)
list2env(data, envir = .GlobalEnv)
#adding a noise variable
X <- cbind(X,rnorm(n))



```

```{r}



blcr_pg_gibbs <- function(X, Y, G = 2, burnin = 500, n_samples = 1000, thin = 1, verbose = TRUE){
  #X is an (nxp)-matrix of covariates.
  #Y is an (nxM)-matrix of categorical responses.
  #G is the number of latent classes.
  
  #getting the number of iterations we need
  
  n_iter <- thin*n_samples + burnin
  
  #Initialising variables
  init <- initialise_variables_polyagamma(G = G,X = X, Y = Y)

  Y = init$Y 
  X = init$X 
  print(X)
  theta = init$theta 
  alpha  = init$alpha 
  beta = init$beta
  print(beta)
  w = init$w
  z = init$z 
  C = init$C 
  n = init$n 
  M = init$M
  G = init$G 
  K = init$K 
  p = init$p 
  Y_flat = init$Y_flat 
  I = init$I 
  J = init$J 
  G_0 = init$G_0 
  K_0 = init$K_0 
  Omega = init$Omega 
  omega = init$omega
  beta_cov = init$beta_cov 
  beta_cov_inv = init$beta_cov_inv 
  beta_cov_inv_chol = init$beta_cov_inv_chol 
  beta_prior_mean = init$beta_prior_mean 
  beta_prior_cov = init$beta_prior_cov 
  beta_prior_cov_inv = init$beta_prior_cov_inv  
  gamma = init$gamma 
  beta_mean = init$beta_mean 
  beta <- init$beta
  eta = init$eta
  
  beta_samples <- array(0, dim = c(dim(beta),n_iter))
  omega_samples <- array(0, dim = c(dim(omega),n_iter))
  w_samples <- array(0, dim = c(dim(w),n_iter))
  z_samples <- array(0, dim = c(dim(z),n_iter))
  theta_samples <- array(0, dim = c(dim(theta),n_iter))
  
  #beta_samples_unfixed <- array(0, dim = c(dim(beta),n_iter))
  #omega_samples_unfixed <- array(0, dim = c(dim(omega),n_iter))
  #w_samples_unfixed <- array(0, dim = c(dim(w),n_iter))
  #z_samples_unfixed <- array(0, dim = c(dim(z),n_iter))
  #theta_samples_unfixed <- array(0, dim = c(dim(theta),n_iter))
  
  cost_matrices <- array(0, dim = c(G,G,n_iter))
  perms <- matrix(0,nrow = G, ncol = n_iter)
  permuted_cost_matrices <-array(0, dim = c(G,G,n_iter))

  
  #Update steps
  
  for (count in 1:n_iter){
    
    if(count == (burnin+1)){
      z_init <- z
    }

    S <- S_update(Y_flat = Y_flat,I = I, J = J, G_0 = G_0, K_0 = K_0, M = M, z = z, G = G)
  
    theta <- theta_update(alpha = alpha, G = G, M = M, K = K, S = S, theta = theta)

    mu <- mu_update(X = X,beta = beta)
    
    exp_mu <- exp(mu)
  
    C <- C_update(exp_mu = exp_mu, mu = mu, G = G, C = C)
  
    eta <- eta_update(mu = mu, C = C)
  
    gamma <- gamma_update(eta = eta)

    log_gamma <- log(gamma)

    log_theta <- log(theta)
  
    w <- w_update(log_gamma = log_gamma,log_theta = log_theta,Y = Y,G = G,n = n,M = M,K = K)
  
    z <- z_update(w)
    
    kappa <- kappa_update(z)
    
    omega_up <- omega_update(eta = eta, mu = mu, G = G, n = n, omega = omega, Omega = Omega)
    
    omega <- omega_up$omega

    Omega <- omega_up$Omega

    beta_up <- beta_cov_mean_update(Omega = Omega, beta_prior_cov = beta_prior_cov, beta_prior_mean = beta_prior_mean, kappa = kappa, C = C, X = X, G = G, beta_prior_cov_inv = beta_prior_cov_inv, beta_cov_inv = beta_cov_inv, beta_cov_inv_chol = beta_cov_inv_chol, beta_cov = beta_cov, beta_mean = beta_mean)

    beta_cov <- beta_up$beta_cov

    beta_mean <- beta_up$beta_mean

    beta <- beta_update(beta_mean = beta_mean, beta_cov = beta_cov, G = G, beta = beta)
    
    if (count>=burnin+1){
      A_mat <- t(z_init)%*%z
      optimal_permutation <- matchClasses(A_mat, method = "exact", verbose = FALSE)
      perms[,count] <- optimal_permutation
      cost_matrices[,,count] <- A_mat
      permuted_A_mat <- A_mat[, optimal_permutation]
      permuted_cost_matrices[,,count] <- permuted_A_mat
    }

    beta_samples[,,count] <- beta
  
    omega_samples[,,count] <- omega
  
    z_samples[,,count] <- z
    
    w_samples[,,count] <- w
      
    theta_samples[,,,count] <- theta

  
    if (verbose == TRUE && count %% 500 == 0){
      print(paste(count,' of ',n_iter, ' completed.'))
      print(beta)
      print(ncol(exp_mu))
    }
  }
  
  #post-processing steps
  #removing burnin
  beta_samples_burned <- beta_samples[,,-(1:burnin)]
  omega_samples_burned <- omega_samples[,,-(1:burnin)]
  z_samples_burned <- z_samples[,,-(1:burnin)]
  w_samples_burned <- w_samples[,,-(1:burnin)]
  theta_samples_burned <- theta_samples[,,,-(1:burnin)]
  perms_burned <- perms[,-(1:burnin)]
  #thinning
  beta_samples_clean <- beta_samples_burned[,,seq(1,dim(beta_samples_burned)[3], by = thin)]
  omega_samples_clean <- omega_samples_burned[,,seq(1,dim(omega_samples_burned)[3], by = thin)]
  z_samples_clean <- z_samples_burned[,,seq(1,dim(z_samples_burned)[3], by = thin)]
  w_samples_clean <- w_samples_burned[,,seq(1,dim(w_samples_burned)[3], by = thin)]
  theta_samples_clean <- theta_samples_burned[,,,seq(1,dim(theta_samples_burned)[4], by = thin)]
  perms_clean <- perms_burned[,seq(1,dim(perms_burned)[2], by = thin)]
  
  #parameter means and standard deviations
  beta_estimate <- apply(beta_samples_clean,c(1,2), mean)
  omega_estimate <- apply(omega_samples_clean,c(1,2), mean)
  theta_estimate <- apply(theta_samples_clean,c(1,2,3), mean)
  beta_sd <- apply(beta_samples_clean,c(1,2), sd)
  omega_sd <- apply(omega_samples_clean,c(1,2), sd)
  theta_sd <- apply(theta_samples_clean,c(1,2,3), sd)
  
  mu_est <- X%*%beta_estimate
  exp_mu_est <- exp(mu_est)
  gamma_est <- exp_mu_est/rowSums(exp_mu_est)
  class_membership <- apply(gamma_est,1,which.max)
  
  pi <- numeric(G)
  for (g in 1:G){
    pi[g] <- length(class_membership[class_membership == g])/length(class_membership)
  }
  
  return(list(beta_estimate = beta_estimate, omega_estimate = omega_estimate, theta_estimate = theta_estimate, beta_sd = beta_sd, omega_sd = omega_sd, theta_sd = theta_sd, class_membership = class_membership, pi = pi, beta_samples = beta_samples_clean, omega_samples = omega_samples_clean, theta_samples = theta_samples_clean, z_samples = z_samples_clean, perms = perms_clean, cost_matrices = cost_matrices, permuted_cost_matrices = permuted_cost_matrices, w_samples = w_samples_clean))
  
  #probably a few other outputs that I could include in here as well
  
  #Note that the estimated beta is actually the transpose, since the sim_data function that I made takes the columns to be beta_g and the sampler takes the rows to be beta_g
  
  #This can also do with some optimisation since its not particularly fast at the moment
}

```

```{r}

n_samples <- 10000
burnin <- 0
set.seed(123)

BLCR_PG_fit1 <- blcr_pg_gibbs(X = X,Y = Y, G = 3, burnin = burnin, n_samples = n_samples, thin = 2, verbose = TRUE)



```


Testing relabelling here
```{r}

z_samples <- BLCR_PG_fit1$z_samples
w_samples <- BLCR_PG_fit1$w_samples
z_mat <- matrix(0, nrow = n_samples, ncol = n)
for (iter in 1:n_samples){
  temp <- z_samples[,,iter]
  temp_row <- apply(temp,1,which.max)
  z_mat[iter,] <- temp_row 
}
w_samples_reshape <- aperm(w_samples,c(3,1,2))
ls <- label.switching(method = "STEPHENS", z = z_mat, K = G, p = w_samples_reshape)


```



Estimates here 
```{r}

beta_estimate <- BLCR_PG_fit1$beta_estimate
theta_estimate <- BLCR_PG_fit1$theta_estimate
beta_samples <- BLCR_PG_fit1$beta_samples
theta_samples <- BLCR_PG_fit1$theta_samples
perms <- BLCR_PG_fit1$perms

#applying permutations to the parameter samples
reordered_beta_samples <- array(0, dim = dim(beta_samples))  # Initialize
for (i in seq_len(dim(beta_samples)[3])) {
  reordered_beta_samples[,,i] <- beta_samples[, perms[, i], i]
}



reordered_theta_samples <- array(0, dim = dim(theta_samples))
for (i in seq_len(dim(theta_samples)[4])) {
  reordered_theta_samples[,,,i] <- theta_samples[perms[,i], , ,i]
}


beta_estimate
#theta_estimate

apply(reordered_beta_samples, c(1,2), mean)


subtracted_beta_samples <- reordered_beta_samples

for (count in 1:(n_samples)){
  baseline <- reordered_beta_samples[,G,count]
  subtracted_beta_samples[,,count] <- reordered_beta_samples[,,count] - baseline
}

apply(subtracted_beta_samples, c(1,2), mean)
```

Trace plots here - some here are better than others
```{r}

plot(beta_samples[1,1,], type = 'l')
plot(beta_samples[1,2,], type = 'l')
plot(beta_samples[2,1,], type = 'l')
plot(beta_samples[2,2,], type = 'l')

```

Density plots
```{r}

plot(density(beta_samples[1,1,]))
plot(density(beta_samples[1,2,]))
plot(density(beta_samples[2,1,]))
plot(density(beta_samples[2,2,]))

```























































Debug
```{r}

list2env(data, envir = .GlobalEnv)
X <- cbind(X,rnorm(n))
init <- initialise_variables_polyagamma(G = G,X = X, Y = Y)
Y = init$Y 
X = init$X 
theta = init$theta 
alpha  = init$alpha 
beta = init$beta
w = init$w
z = init$z 
C = init$C 
n = init$n 
M = init$M
G = init$G 
K = init$K 
p = init$p 
Y_flat = init$Y_flat 
I = init$I 
J = init$J 
G_0 = init$G_0 
K_0 = init$K_0 
Omega = init$Omega 
omega = init$omega
beta_cov = init$beta_cov 
beta_cov_inv = init$beta_cov_inv 
beta_cov_inv_chol = init$beta_cov_inv_chol 
beta_prior_mean = init$beta_prior_mean 
beta_prior_cov = init$beta_prior_cov 
beta_prior_cov_inv = init$beta_prior_cov_inv  
gamma = init$gamma 
beta_mean = init$beta_mean 
beta <- init$beta
eta = init$eta

n_iter <- 20000
burnin <- 5000

beta_samples <- array(0, dim = c(dim(beta), n_iter))
theta_samples <- array(0, dim = c(dim(theta), n_iter))
perms <- matrix(0, nrow = G, ncol = (n_iter-burnin))
cost_matrices <- array(0, dim = c(G,G,n_iter-burnin))
permuted_cost_matrices <- array(0, dim = c(G,G,n_iter-burnin))

for (count in 1:n_iter){
  if(count == (burnin+1)){
      z_init <- z
  }

  S <- S_update(Y_flat = Y_flat,I = I, J = J, G_0 = G_0, K_0 = K_0, M = M, z = z, G = G)
  
  theta <- theta_update(alpha = alpha, G = G, M = M, K = K, S = S, theta = theta)

  mu <- mu_update(X = X,beta = beta)
    
  exp_mu <- exp(mu)
  
  C <- C_update(exp_mu = exp_mu, mu = mu, G = G, C = C)
  
  eta <- eta_update(mu = mu, C = C)
  
  gamma <- gamma_update(eta = eta)

  log_gamma <- log(gamma)

  log_theta <- log(theta)
  
  w <- w_update(log_gamma = log_gamma,log_theta = log_theta,Y = Y,G = G,n = n,M = M,K = K)
  
  z <- z_update(w)
    
  kappa <- kappa_update(z)
    
  omega_up <- omega_update(eta = eta, mu = mu, G = G, n = n, omega = omega, Omega = Omega)
    
  omega <- omega_up$omega

  Omega <- omega_up$Omega

  beta_up <- beta_cov_mean_update(Omega = Omega, beta_prior_cov = beta_prior_cov, beta_prior_mean = beta_prior_mean, kappa = kappa, C = C, X = X, G = G, beta_prior_cov_inv = beta_prior_cov_inv, beta_cov_inv = beta_cov_inv, beta_cov_inv_chol = beta_cov_inv_chol, beta_cov = beta_cov, beta_mean = beta_mean)

  beta_cov <- beta_up$beta_cov

  beta_mean <- beta_up$beta_mean

  beta <- beta_update(beta_mean = beta_mean, beta_cov = beta_cov, G = G, beta = beta)

  beta_samples[,,count] <- beta
  
  theta_samples[,,,count] <- theta
  
  if (count>=burnin+1){
      A_mat <- t(z_init)%*%z
      optimal_permutation <- matchClasses(A_mat, method = "exact", verbose = FALSE)
      perms[,count-burnin] <- optimal_permutation
      cost_matrices[,,count-burnin] <- A_mat
      permuted_A_mat <- A_mat[, optimal_permutation]
      permuted_cost_matrices[,,count-burnin] <- permuted_A_mat
    }

  if (count %% 500 == 0){
      print(paste(count,' of ',n_iter, ' completed.'))
      print(beta)
      print(ncol(exp_mu))
  }
}

```








