---
title: "Polya-Gamma multinomial logistic regression implementation"
output: html_notebook
---
```{r}

library(nnet)
library(BayesLogit)
library(MASS)
library(nnet)

```


Simulating some data
```{r}
n <- 10000
G <- 3 #was 5
p <- 1 #was 2
set.seed(123)
#X1 <- rnorm(n)   
#X2 <- rnorm(n)   
#X <- cbind(1, X1, X2)  
X1 <- matrix(rnorm(p*n), nrow = n)
X <- cbind(1,X1)


true_beta <- matrix(c(-1,  2, 5, -3),  
               ncol = p+1, byrow = TRUE)

true_mu <- X %*% t(true_beta)  

true_exp_mu <- exp(true_mu)
true_exp_mu <- cbind(true_exp_mu,1)
#probs <- cbind(true_exp_mu/(1+rowSums(true_exp_mu)),1-true_exp_mu/(1+rowSums(true_exp_mu)))
probs <- true_exp_mu / rowSums(true_exp_mu)


categories <- apply(probs, 1, function(p) sample(1:G, size = 1, prob = p))

#simulated_data <- data.frame(category = categories, X1 = X1, X2 = X2)
simulated_data <- data.frame(category = categories, X1 = X1)


head(simulated_data)
```


This works! - not anymore, the C is causing issues i think
```{r}


G <- 2
p <- 1
X <- cbind(1,simulated_data$X1)
simulated_data$category <- as.factor(simulated_data$category)
z <- model.matrix(~category - 1, data = simulated_data)
kappa <- z-1/2
beta <- rbind(matrix(rnorm((G-1)*(p+1)), nrow = G-1),0)


mu <- X%*%t(beta)
C <- matrix(rnorm((n)*(G)), nrow = n)
eta <- mu  - C
beta_prior_mean <- rep(0,p+1)
beta_prior_cov <- diag(p+1)
beta_prior_cov_inv <- beta_prior_cov #Since beta_prior_mean = I

omega <- matrix(rpg(n*G), nrow = n)
Omega <- array(0, dim = c(n,n,(G-1)))
for(g in 1:(G-1)){
  Omega[,,g] <- diag(omega[,g])
}

beta_cov <- array(0, dim = c(p+1,p+1,G-1))
beta_cov_inv <- array(0, dim = c(p+1,p+1,G-1))
beta_cov_inv_chol <- array(0, dim = c(p+1,p+1,G-1))
beta_mean <- matrix(0, nrow = (G-1), ncol = (p+1) )

for (g in 1:(G-1)){
  beta_cov_inv[,,g] <- t(X)%*%(Omega[,,g]%*%X) + beta_prior_cov_inv
  beta_cov_inv_chol[,,g] <- chol(beta_cov_inv[,,g])
  beta_cov[,,g] <- chol2inv(beta_cov_inv_chol[,,g])
  beta_mean[g,] <- beta_cov[,,g]%*%(t(X)%*%(kappa[,g] - Omega[,,g]%*%C[,g]) + beta_prior_cov_inv%*%beta_prior_mean)
  beta[g,] <- mvrnorm(1,mu = beta_mean[g,], Sigma = beta_cov[,,g])
}

for(g in 1:(G-1)){
  for (i in 1:n){
    #omega[i,g] <- rpg(1,1,eta[i,g])
    omega[i,g] <- rpg(1,1,mu[i,g])
  }
  Omega[,,g] <- diag(omega[,g])
}

n_iter <- 1000
omega_samples <- array(0, dim = c(dim(omega),n_iter))
beta_samples <- array(0, dim = c(dim(beta),n_iter))

for (count in 1:n_iter){
  mu <- X%*%t(beta)
  exp_mu <- exp(mu)
  for (i in 1:n){
    for (g in 1:G){
      exp_mu_subset <- exp_mu[i, -g]
      max_exp_mu <- max(exp_mu_subset)
      C[i,g] <- log(sum(exp(log(exp_mu_subset) - log(max_exp_mu)))) + log(max_exp_mu)
    }
  }
  eta <- mu  - C
  for (g in 1:(G-1)){
    beta_cov_inv[,,g] <- t(X)%*%(Omega[,,g]%*%X) + beta_prior_cov_inv
    beta_cov_inv_chol[,,g] <- chol(beta_cov_inv[,,g])
    beta_cov[,,g] <- chol2inv(beta_cov_inv_chol[,,g])
    beta_mean[g,] <- beta_cov[,,g]%*%(t(X)%*%(kappa[,g] - Omega[,,g]%*%C[,g]) +         beta_prior_cov_inv%*%beta_prior_mean)
    beta[g,] <- mvrnorm(1,mu = beta_mean[g,], Sigma = beta_cov[,,g])
    for (i in 1:n){
      omega[i,g] <- rpg(1,1,eta[i,g])
    }
    Omega[,,g] <- diag(omega[,g])
  }
  for (i in 1:n){
    omega[i,G] <- rpg(1,1,eta[i,G])
  }
  beta_samples[,,count] <- beta
  omega_samples[,,count] <- omega
  print(count)
  
}

```








Gonna just try it for the binary case first

```{r}

n <- 1000
G <- 2
p <- 1
true_beta <- c(-1,3)
X1 <- rnorm(n)
X <- cbind(1,X1)
true_mu <- X%*%true_beta
exp_true_mu <- exp(true_mu)
exp_true_mu <- cbind(exp_true_mu,1)
probs <- exp_true_mu / rowSums(exp_true_mu)
categories <- apply(probs, 1, function(p) sample(1:G, size = 1, prob = p))
simulated_data <- data.frame(category = categories, X1 = X1)


```



```{r}
simulated_data$catfactor <- factor(simulated_data$category)
z <- ifelse(simulated_data$catfactor == 1, 1,0)
kappa <- z - 1/2
beta <- rnorm(p+1)
beta_prior_mean <- rep(0, p+1)
beta_prior_cov <- diag(1,p+1)
beta_prior_cov_inv <- chol2inv(chol(beta_prior_cov))
beta_prior_cov_times_mean <- beta_prior_cov_inv%*%beta_prior_mean
omega <- numeric(n)
mu <- X%*%beta
omega <- rpg(n,1,mu)
Omega <- diag(omega)

beta_cov <- chol2inv(chol(t(X)%*%Omega%*%X + beta_prior_cov_inv))
beta_mean <- beta_cov%*%(t(X)%*%kappa + beta_prior_cov_times_mean)

beta <- mvrnorm(1,beta_mean,beta_cov)
n_iter <- 100000
count <- 1
omega_samples <- matrix(0, nrow = n, ncol = n_iter)
beta_samples <- matrix(0, nrow = p+1, ncol = n_iter)

while(count<n_iter){
  mu <- X%*%beta
  omega <- rpg(n,1,mu)
  Omega <- diag(omega)

  beta_cov <- chol2inv(chol(t(X)%*%Omega%*%X + beta_prior_cov_inv))
  beta_mean <- beta_cov%*%(t(X)%*%kappa + beta_prior_cov_times_mean)

  beta <- mvrnorm(1,beta_mean,beta_cov)
  count <- count + 1
  if(count %% 500 == 0){
    print(count)
  }
  beta_samples[,count] <- beta
  omega_samples[,count] <- omega
}
```


Now for the multinomial case - I'll start with G = 3 anyway
```{r}

n <- 1000
G <- 3
p <- 1
true_beta <- matrix(c(-0.3,0.9,1,-1), nrow = G-1, byrow = TRUE)
X1 <- rnorm(n)
X <- cbind(1,X1)
true_mu <- X%*%true_beta
exp_true_mu <- exp(true_mu)
true_gamma <- cbind(exp_true_mu/(1+rowSums(exp_true_mu)), 1/(1+rowSums(exp_true_mu)))
categories <- apply(true_gamma, 1, function(p) sample(1:G, size = 1, prob = p))
simulated_data <- data.frame(category = categories, X1 = X1)

```


```{r}
simulated_data$catfactor <- factor(simulated_data$category)
z <- model.matrix(~ catfactor - 1, data = simulated_data)
kappa <- z - 1/2
beta_G <- rep(0,p+1)
beta <- rbind(matrix(rnorm((G-1)*(p+1)), nrow = (G-1)))
beta_prior_mean <- rep(0,p+1)
beta_prior_cov <- diag(1,p+1)
beta_prior_cov_inv <- chol2inv(chol(beta_prior_cov))
beta_prior_cov_times_mean <- beta_prior_cov_inv%*%(beta_prior_mean)


mu <- X%*%t(beta)
exp_mu <- exp(mu)
C <- matrix(, nrow = n, ncol = (G-1))
for (g in 1:(G-1)){
  for (i in 1:n){
    C[i,g] <- log(1 + sum(exp(mu[i,-g])))
  }
}
eta <- mu - C
omega <- matrix(0, nrow = n, ncol = G-1)
Omega <- array(0,dim = c(n,n,G-1))
for (g in 1:(G-1)){
  for (i in 1:n){
    omega[i,g] <- rpg(1,1,eta[i,g]) 
  }
  Omega[,,g] <- diag(omega[,g])
}

beta_cov_inv <- array(,dim = c(p+1,p+1,G-1))
beta_cov <- array(,dim = c(p+1,p+1,G-1))
beta_mean <- matrix(,nrow = G-1,ncol = p+1)
for (g in 1:(G-1)){
  beta_cov_inv[,,g] <- t(X)%*%(Omega[,,g]%*%X) + beta_prior_cov_inv
  beta_cov[,,g] <- chol2inv(chol(beta_cov_inv[,,g]))
  beta_mean[g,] <- beta_cov[,,g]%*%(t(X)%*%(kappa[,g] - Omega[,,g]%*%C[,g]) + beta_prior_cov_times_mean)
  beta[g,] <- mvrnorm(1,beta_mean[g,],beta_cov[,,g])
}




n_iter <- 1000
beta_samples <- array(0,dim = c(G-1,p+1,n_iter))


for (count in 1:n_iter){
  mu <- X%*%t(beta)
  exp_mu <- exp(mu)
  for (g in 1:(G-1)){
    for (i in 1:n){
      C[i,g] <- log(1 + sum(exp_mu[i,-g]))
    }
  }
  eta <- mu - C
  for (g in 1:(G-1)){
    for (i in 1:n){
      omega[i,g] <- rpg(1,1,eta[i,g]) 
    }
    Omega[,,g] <- diag(omega[,g])
  }

  for (g in 1:(G-1)){
    beta_cov_inv[,,g] <- t(X)%*%(Omega[,,g]%*%X) + beta_prior_cov_inv
    beta_cov[,,g] <- chol2inv(chol(beta_cov_inv[,,g]))
    beta_mean[g,] <- beta_cov[,,g]%*%(t(X)%*%(kappa[,g] - Omega[,,g]%*%C[,g]) + beta_prior_cov_times_mean)
    beta[g,] <- mvrnorm(1,beta_mean[g,],beta_cov[,,g])
  }
  beta_samples[,,count] <- beta 
  print(count)
}


simulated_data$catfactor <- relevel(simulated_data$catfactor, ref = 2)
glm_fit <- multinom(catfactor ~ X1, data = simulated_data)




```



